<a href="https://colab.research.google.com/github/Seb300803/Analisis-de-datosss/blob/main/Actividad2_(valores_nulos).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [16]:
#convertir a dataframe
df= pd.read_csv("inmuebles2.csv", skiprows=1)
df.head(5)

,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,5,5,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María

In [18]:
df2= df.drop(['0','Referencia'], axis=1)
df2

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [19]:
valores_nulos=df2.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

Metodo de sustitucion de valores nulos

In [20]:
df3=df2.copy()

In [23]:
df3["Superficie"]=df3["Superficie"].fillna(round(df2["Superficie"].mean(),1))
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [41]:
#tabla actualizada
valores_nulos=df3.isnull().sum()
valores_nulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64

In [25]:
df3["Precio Venta"]=df3["Precio Venta"].fillna(round(df2["Precio Venta"].median(),1))
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [27]:
df3["Fecha Alta"]=df3["Fecha Alta"].fillna(10)
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [29]:
df3["Fecha Venta"]=df3["Fecha Venta"].fillna("2030-06-19 00:00:00")
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [31]:
df3["Tipo"]=df3["Tipo"].fillna(method="ffill")
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [33]:
df3["Operación"]=df3["Operación"].fillna(method="bfill")
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [35]:
df3["Provincia"]=df3["Provincia"].fillna(method="bfill")
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [40]:
df3["Vendedor"]=df3["Vendedor"].fillna(method="ffill")
df3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,María
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,María
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,María
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,María
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,María

In [43]:
df4= df2.dropna()
df4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
5,2004-01-03 00:00:00,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05 00:00:00,Pedro
7,2004-01-03 00:00:00,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31 00:00:00,Jesús
...,...,...,...,...,...,...,...,...
3016,2006-12-30 00:00:00,Casa,Alquiler,Barcelona,264.0,1060488.0,2007-04-28 00:00:00,Joaquín
3017,2006-12-31 00:00:00,Oficina,Venta,Lleida,69.0,483828.0,2007-05-05 00:00:00,Pedro
3030,2007-01-07 00:00:00,Industrial,Alquiler,Lleida,196.0,904344.0,2007-04-20 00:00:00,Pedro
3042,2007-01-09 00:00:00,Local,Venta,Lleida,92.0,709596.0,2007-04-17 00:00:00,Carmen
3045,2007-01-10 00:00:00,Parking,Venta,Barcelona,233.0,1077858.0,2007-04-30 00:00:00,María